In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


%load_ext autoreload
%autoreload 2

In [17]:
np.random.seed(10)
print(np.random.randint(2))
print(np.random.randint(2))

1
1


In [5]:
n = 5
grid = np.random.choice([0, 1, 2, 3], size=(n, n)) 
print(grid)

try:
    print(grid[0][1])
except IndexError:
    pass

try:
    print(grid[1][6])
except IndexError:
    pass

try:
    print(grid[3][2])
except IndexError:
    pass

[[2 0 2 1 1]
 [1 3 1 0 3]
 [0 0 3 2 0]
 [3 3 2 1 1]
 [3 1 3 1 0]]
0
2
